stages:
  - build
  - deploy

variables:
  DEPLOY_DIR: "/usr/share/nginx/html/beacon_console/"

build_job:
  stage: build
  tags:
    - webapps
  script:
    - pnpm install --registry=https://registry.npm.taobao.org
    - pnpm run build
  artifacts:
    paths:
      - dist/

deploy_job:
  stage: deploy
  tags:
    - webapps
  script:
    - rm -rf $DEPLOY_DIR
    - mkdir -p $DEPLOY_DIR
    - cp -r $CI_PROJECT_DIR/dist/* $DEPLOY_DIR
