name: Deploy

on:
  push:
    branches:
      - main # 可以根据你的需要修改触发条件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm # 修改为 pnpm 缓存

      - name: Install dependencies
        run: pnpm install # 使用 pnpm 安装依赖

      - name: Build
        run: pnpm run build:gh-pages # 使用 pnpm 进行构建

      - name: Install fs-extra
        run: pnpm add fs-extra # 临时安装 fs-extra 依赖

      - name: Copy index.html to 404.html
        run: |
          node -e "
          const fs = require('fs-extra');
          const path = require('path');
          const source = path.join(__dirname, 'dist', 'index.html');
          const destination = path.join(__dirname, 'dist', '404.html');
          fs.copy(source, destination)
            .then(() => console.log('index.html was copied to 404.html'))
            .catch(err => {
              console.error('Error copying index.html to 404.html:', err);
              process.exit(1);
            });
          "

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
