name: Deploy

on:
  push:
    branches:
      - main # 可以根据你的需要修改触发条件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm # 修改为 pnpm 缓存

      - name: Install dependencies
        run: pnpm install # 使用 pnpm 安装依赖

      - name: Build
        run: pnpm run build # 使用 pnpm 进行构建

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
